name: Update GCD+ Logo

on:
  push:
    paths:
      - 'logo.png'

jobs:
  update_logo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update GCD+ Logo
        run: cp logo.png /path/to/your/documentation/folder/logo.png

      - name: Commit and Push Logo Update
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add /path/to/your/documentation/folder/logo.png
          git commit -m "Update GCD+ logo"
          git push
          
